### ISSUE TITLE
Rack crash when trying opening NoteTracker on Windows 10 Pro

### ISSUE THREAD

**Issue by caecos** [cclark2a/SchmickleWorks#10]
Assertion failed!

Program: C:\msys64\home\caeco\rack\Rack.exe
File: src/NoteTakerDisplay.cpp, Line 410

Expression: 0
make: *** [Makefile:61: run] Error 3

**Comment by cclark2a** [comment]
It looks like the saved data is corrupt. Can you launch Rack from a terminal window and paste the output here? It should print "to do: add type ##" just before the crash.

Here's some other things you can try:
open autosave.vcv and send me the part that begins

{
      "plugin": "SchmickleWorks-NoteTaker",

and ends:

**Comment by cclark2a** [comment]
"pos": [
        0,
        0
      ]
    },

The part that is corrupt begins:

      "data": {
        "allNotes": [

Or, try starting the patch from scratch. I'll try that locally to see if that fails for me as well.

**Comment by cclark2a** [comment]
OK, glad I wrote that, sort of. :) 
I can repro the crash just be deleting and adding NoteTaker back. Working on a fix.

**Comment by caecos** [comment]
[22.289 debug src/NoteTakerParseMidi.cpp:7] parseMidi start
[22.289 debug src/NoteTakerDebug.cpp:96] notes: 2
[22.289 debug src/NoteTakerDebug.cpp:110] 0 midi header [255] 0 format=0
[22.289 debug src/NoteTakerDebug.cpp:110] 0 track end [255] -1
[22.311 debug src/NoteTakerDisplay.cpp:409] to do: add type 109

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : cclark2a <notifications@github.com>
Envoyé : Sunday, March 24, 2019 6:06:36 PM
À : cclark2a/SchmickleWorks
Cc : caecos; Author
Objet : Re: [cclark2a/SchmickleWorks] Rack crash when trying opening NoteTracker on Windows 10 Pro (#10)


OK, glad I wrote that, sort of. :)
I can repro the crash just be deleting and adding NoteTaker back. Working on a fix.

**Comment by cclark2a** [comment]
Thanks. The bug is that the code thinks there are more notes to draw than there actually are, so it walks off the end of the array. Debugging now.

**Comment by caecos** [comment]
Cannot save the autosave.vcv file…

**Comment by cclark2a** [comment]
Don't worry about it, I don't need it.

**Comment by cclark2a** [comment]
I've uploaded a fix. Let me know if that helps.

**Comment by caecos** [comment]
OK I'll try it now...

**Comment by caecos** [comment]
Works fine...thanks...
