### ISSUE TITLE
load fail latest pull

### ISSUE THREAD

**Issue by davephillips** [cclark2a/SchmickleWorks#11]
`[0.186 warn src/plugin.cpp:90] Failed to load library ./plugins/SchmickleWorks/plugin.so: ./plugins/SchmickleWorks/plugin.so: undefined symbol: _ZN13NoteDurations7ClosestEii`

**Comment by cclark2a** [comment]
You're absolutely right. Doh! I uploaded a fix.

As a reward, you can now import Google Bach improvisations :)   To try this out, hook up all four CV and gates, and press 'File'  (far right top row), scroll the horizontal wheel to '9', move the vertical wheel to 'load', then press 'RUN'. 

To load your own MIDI, go to https://www.google.com/doodles/celebrating-johann-sebastian-bach , create a score, click on the MIDI button to save bachpiece.mid in your Downloads folder. Then copy that file to plugins/SchmickleWorks/midi as '#.mid' where '#' is a small number.

Let me know if that works for you. And, thanks again for the bug report.
