### ISSUE TITLE
Compiling error 1

### ISSUE THREAD

**Issue by caecos** [cclark2a/SchmickleWorks#2]
Won't compile with MSYS2 under Windows 10...get error 1...

**Comment by caecos** [comment]
In file included from ../../include/rack.hpp:12,
                 from src/NotesPlugin.hpp:5,
                 from src/NotesPlugin.cpp:1:
../../include/helpers.hpp:10:8: note: candidate: 'template<class TModule, class TModuleWidget, class ... Tags> rack::Model* rack::createModel(std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, Tags ...)'
 Model *createModel(std::string author, std::string slug, std::string name, Tags... tags) {
        ^~~~~~~~~~~
../../include/helpers.hpp:10:8: note:   template argument deduction/substitution failed:
src/NotesPlugin.cpp:495:99: note:   couldn't deduce template parameter 'TModuleWidget'
     p->addModel(createModel<NotesModuleWidget>("Template", "MyModule", "My Module", OSCILLATOR_TAG));
                                                                                                   ^
make: *** [../../compile.mk:65: build/src/NotesPlugin.cpp.o] Error 1

**Comment by cclark2a** [comment]
older files will be removed soon

**Comment by caecos** [comment]
Thanks

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cclark2a** [comment]
fixed
