### ISSUE TITLE
Still won't compile under Windows...

### ISSUE THREAD

**Issue by caecos** [cclark2a/SchmickleWorks#3]
$ make
g++  -Wsuggest-override -std=c++11  -DSLUG=SchmickleWorks-NoteTaker -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/NoteTakerDebug.cpp.o src/NoteTakerDebug.cpp
In file included from src/NoteTakerDebug.cpp:1:
src/NoteTaker.hpp: In member function 'bool NoteTaker::setSelectStart(unsigned int)':
src/NoteTaker.hpp:161:14: error: 'insertButton' was not declared in this scope
         if (!insertButton->ledOn) {
              ^~~~~~~~~~~~
src/NoteTaker.hpp:161:14: note: suggested alternative: 'bndToolButton'
         if (!insertButton->ledOn) {
              ^~~~~~~~~~~~
              bndToolButton
make: *** [../../compile.mk:65: build/src/NoteTakerDebug.cpp.o] Error 1

**Comment by SteveRussell33** [comment]
Same error here on Win10

**Comment by caecos** [comment]
Not the same...in the first issue the last line was: make: *** [../../compile.mk:65: build/src/NotesPlugin.cpp.o] Error 1...

**Comment by cclark2a** [comment]
Let me know if a3d32f2c4a57960b053ac5342e6c39ef234b5609 works for you

**Comment by cclark2a** [comment]
I'm setting up a Mac, so I will test there as well to see if I can make this work

**Comment by SteveRussell33** [comment]
Compiles under Win10.
Crashes VCV rack adding module to patch

**Comment by cclark2a** [comment]
Can you run 'make debug' and paste the output here?

**Comment by cclark2a** [comment]
Deleting the module triggers a crash because I'm doing something wrong with the font shared_ptr . I cribbed the code from Fundementals/Scope so I'll look there to see if I can see the bug.

**Comment by cclark2a** [comment]
I can repro the crash adding the module. Working on it.

**Comment by cclark2a** [comment]
I can add the module without crashing, but VCV Rack still crashes when I exit. It looks like I am writing off the end of a vector somewhere. This fooled me into thinking it was a font problem but that's not the issue. Still working on it.

**Comment by cclark2a** [comment]
Now it crashes on Windows when I click on the RUN button, but works fine on Mac. I verified, on Mac, I can download source from github, make dist, copy zip to Rack plugins, create NoteTaker module, and use it.

If you know a way to debug memory corruption on MSYS2 MinGW I'd love to hear about it.

**Comment by caecos** [comment]
Thanks... will try it tonight... regards...

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>

________________________________
De : cclark2a <notifications@github.com>
Envoyé : jeudi, février 7, 2019 13:52
À : cclark2a/SchmickleWorks
Cc : caecos; Author
Objet : Re: [cclark2a/SchmickleWorks] Still won't compile under Windows... (#3)


I can add the module without crashing, but VCV Rack still crashes when I exit. It looks like I am writing off the end of a vector somewhere. This fooled me into thinking it was a font problem but that's not the issue. Still working on it.

**Comment by cclark2a** [comment]
all, including memory corruption, should be fixed now
