### ISSUE TITLE
Ports not working

### ISSUE THREAD

**Issue by SteveRussell33** [cclark2a/SchmickleWorks#5]
Only CV and Gate ports 1 allow cable connection

Sidenote: Line 74 of NoteTakerWidget.cpp should be
Model *modelNoteTaker = Model::create<NoteTaker, NoteTakerWidget>("SchmickleWorks", "NoteTakerWidget", "Note Taker", OSCILLATOR_TAG);
This allows it to be found by Author in the module listbox in VCV Rack

**Comment by cclark2a** [comment]
You are correct, I have not yet coded CV and Gate for 2 / 3 / 4 .

**Comment by cclark2a** [comment]
Thanks for the note about Line 74. I also changed it to SEQUENCER_TAG

**Comment by cclark2a** [comment]
My bug was that I had failed to supply the size of the buttons, so they were overlapping most of the plugins. Now CV and Gate 2/3/4 do something. To move a note from one part to another, press the 'part' button (looks like a chord) and move the vertical wheel up or down until the note changes to match the color around the outputs. Still early days, don't expect too much.
