### ISSUE TITLE
no notation display

### ISSUE THREAD

**Issue by davephillips** [cclark2a/SchmickleWorks#9]
Greetings,

With the most recent pulls I'm getting a module with no notation display. Everything else is there, just no notation. A screenshot:

![notetaker-nonotes](https://user-images.githubusercontent.com/7815938/54433200-a62cbd00-4701-11e9-8516-be318cd429e1.png)

Am I missing something ?

**Comment by cclark2a** [comment]
If I choose 'initialize' from the context menu, I can reproduce this. Thanks for letting me know.

**Comment by cclark2a** [comment]
Fixed, sort of. I am in the middle of rewriting some code, so everything is not as stable as I would like. After updating and running, choose 'Initialize' from the context menu to make the notation display appear. The 'add note' button will add to CV 2 (red note) by default (bug), but you can choose CV 1 by pressing the part button (three notes, second from the right top row) and moving the horizontal wheel to the left. 

I'll work on getting things stable and uploading a new baseline in the next day or so.
